learn/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from post.views import index
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^$', index),
	url(r'^post/', include('post.urls',namespace='post')),
	url(r'^users/', include('users.urls',namespace='users')),
	url(r'^todo/', include('todo.urls',namespace='todo')),
 ]
 
urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
 
urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.conf.urls import url
from .views import post_list, post_create, post_update, post_delete, post_detail, form_test, test, comment_delete, reply_view, like

urlpatterns =[
	url(r'^$', post_list, name='index'),
	url(r'^create/$', post_create, name='create'),
	url(r'^update/(?P<slug>[\w\-]+)/$', post_update, name='update'),
	url(r'^delete/(?P<slug>[\w\-]+)$', post_delete, name='delete'),
	url(r'^comment/delete/(?P<pk>[0-9]+)$', comment_delete, name='comment_delete'),
	url(r'^reply/(?P<pk>[0-9]+)$', reply_view, name='reply'),
	url(r'^like/(?P<pk>[0-9]+)$', like, name='like'),
	url(r'^detail/(?P<slug>[\w\-]+)/$', post_detail,name='detail'),
	url(r'^form/$', form_test),
	url(r'^test/$', test)

]

todo/urls.py
from django.conf.urls import url
from .views import index, complete, delete

urlpatterns =[
	url(r'^$', index, name='index'),
	url(r'^complete/(?P<pk>[0-9]+)$', complete, name='complete'),
	url(r'^delete/(?P<pk>[0-9]+)$', delete, name='delete'),
]

todo/models.py
from django.db import models
from django.contrib.auth.models import User




# Create your models here.
class Thing(models.Model):
	
	owner = models.ForeignKey(User,related_name='owner')
	title = models.CharField(max_length=120,verbose_name='Başlıq', blank=False)
	text=models.TextField(verbose_name='Şərh',max_length=1200, null=True, blank=True)
	completed = models.BooleanField(default=False)
	created_to = models.DateTimeField(auto_now_add=True)
	updated_to = models.DateTimeField(auto_now=True)
	updated = models.BooleanField(default=False)
	completed_at = models.DateTimeField(auto_now=True)
	'''def __init__(self, *args, **kwargs):
		super (thing, self).__init__(*args, **kwargs)'''

	class Meta:
		ordering=['-created_to']
	def is_completed(self):
		if self.completed == True:
			return "Tamamlanıb"
		

todo/forms.py
from django import forms
from .models import Thing


class FastCreateForm(forms.ModelForm):
	title = forms.CharField(max_length=120,label="Başlıq", widget=forms.TextInput(attrs={"class":"form-control"}))
	text = forms.CharField(max_length=1200, label="Haqqında", widget=forms.Textarea(attrs={"required":"False", "class":"form-control"}))

	class Meta:
		model = Thing
		fields = ['title','text']

	'''def __init__(self, *args, **kwargs):
		super(CreateThingForm, self).__init__(*args, **kwargs)
		self.fields['text'].widget.attrs['class']='form-control'
		'''

todo/views.py
from django.shortcuts import render, HttpResponse, HttpResponseRedirect, reverse, get_object_or_404, Http404
from .forms import FastCreateForm
from .models import Thing
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator,PageNotAnInteger,EmptyPage
from django.http import JsonResponse

@login_required(login_url='/users/user_login/')
def index(request):
	object_list = Thing.objects.filter(owner=request.user)
	page = request.GET.get('page', 1)
	form = FastCreateForm()
	com = request.GET.get('list', 'uncompleted')
	if com == 'uncompleted':
		object_list = object_list.filter(completed=False)
	elif com == 'all':
		pass
	paginator = Paginator(object_list, 10)
	try:
		object_list = paginator.page(page)
	except PageNotAnInteger:
		object_list = paginator.page(1)
	except EmptyPage:
		object_list = paginator.page(paginator.num_pages)
	if request.method == 'POST':
		form = FastCreateForm(request.POST)
		if form.is_valid():
			data = form.save(commit=False)
			data.owner = request.user
			data.save()
			form = FastCreateForm()
			json = {'success':'true', 'pk':data.pk, 'title':data.title,"created":data.created_to,
			"completed":data.completed,"text":data.text}
			return JsonResponse(data=json)
	return render(request,'todo/index.html', context={'object_list':object_list,'form':form})

@login_required(login_url='/users/user_login/')
def complete(request, pk):
	thing = get_object_or_404(Thing, pk=pk)
	if thing.owner != request.user:
		return HttpResponse('400')
	if thing.completed == True:
		data={'success':False}
	else:
		thing.completed = True
		thing.save()
		data={'success':True}
	return JsonResponse(data=data)

@login_required(login_url='/users/user_login/')
def delete(request, pk):
	thing = get_object_or_404(Thing, pk=pk)
	if thing.owner != request.user:
		return HttpResponse('400')
	thing.delete()
	return JsonResponse(data={"success":True})

templates/todo/index.html
{% extends 'base.html' %}

{% load static %}
{% block title %}ToDo {% endblock %}
{% block kod %} 
<script type="text/javascript" src="{% static 'js/dateformat.js' %}"></script>
<script type="text/javascript" src="{% static 'js/todo.js' %}"></script> 

{% endblock %}
{% block page %}
<div class="container">
<button id="openform" class="btn btn-success">Əlavə et</button>
<form style="display: none;" id="form" method="post" action="">
	{% csrf_token %}
{{form.as_p}}
<input class="btn btn-success" type="submit" value="Əlavə et">
</form>
<hr>
<form id="listform" action="" method="get">
	<div class="form-group">
		<select id="list" name="list" class="form-control">
			{% if request.GET.list == 'all' %}
			<option value="all">Hamısı</option>
			<option value="uncompleted">Tamamlanmayanlar</option>
			{% else %}
			<option value="uncompleted">Tamamlanmayanlar</option>
			<option value="all">Hamısı</option>
			{% endif %}
			
		</select>
		<input style="display: none;" type="submit" name="sub"/>
	</div>
</form>
<hr>
<ul class="list-group">
{% for object in object_list %}
<li href="#" class="list-group-item name">
 <h4>
 	<div class="btn-group pull-right">
	 	
		{% if object.completed == False %}
		<button type="button" url="{% url 'todo:complete' object.pk %}" class="btn btn-success complete">
			<span class="glyphicon glyphicon-check"></span></button>
		{% else %}
		<button class="btn btn-info"><span class="glyphicon glyphicon-ok"></span></button>
		{% endif %}
		<button type="button" url="{% url 'todo:delete' object.pk %}" class="btn btn-danger delete"> <span class="glyphicon glyphicon-trash"></span> </button>
	</div>
	{{object.title}}
	<small>
	 {{object.created_to}} 
	</small>
	
</h4>
		<div style="display: none;" class="detail">
			<hr> 
			Əlavə olunub: {{ object.created_to }} <br>
			{% if object.updated == True %}
			Redaktə olunub: {{object.updated_to}} <br>
			{% endif%}
			{% if object.completed == True %}
			Tamamlanıb: {{ object.completed_at }}<br>
			{% endif %}
			Haqqında:<br>
			{{ object.text }}<br>
		</div>
	
	</li>
{% empty %}
Boş
{% endfor %}
</ul>
{% if object_list.has_other_pages %}
  <ul class="pagination">
    {% if object_list.has_previous %}
      <li><a href="?page={{ object_list.previous_page_number }}{% if request.GET.list %}&list={{request.GET.list}}{% endif %}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in object_list.paginator.page_range %}
      {% if object_list.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}{% if request.GET.list %}&list={{request.GET.list}}{% endif %}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if object_list.has_next %}
      <li><a href="?page={{ object_list.next_page_number }}{% if request.GET.list %}&list={{request.GET.list}}{% endif %}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}

</div>
{% endblock %}