learn/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from post.views import index
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^$', index),
	url(r'^post/', include('post.urls',namespace='post')),
	url(r'^users/', include('users.urls',namespace='users')),
	url(r'^todo/', include('todo.urls',namespace='todo')),
 ]
 
urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
 
urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.conf.urls import url
from .views import post_list, post_create, post_update, post_delete, post_detail, form_test, test, comment_delete, reply_view, like

urlpatterns =[
	url(r'^$', post_list, name='index'),
	url(r'^create/$', post_create, name='create'),
	url(r'^update/(?P<slug>[\w\-]+)/$', post_update, name='update'),
	url(r'^delete/(?P<slug>[\w\-]+)$', post_delete, name='delete'),
	url(r'^comment/delete/(?P<pk>[0-9]+)$', comment_delete, name='comment_delete'),
	url(r'^reply/(?P<pk>[0-9]+)$', reply_view, name='reply'),
	url(r'^like/(?P<pk>[0-9]+)$', like, name='like'),
	url(r'^detail/(?P<slug>[\w\-]+)/$', post_detail,name='detail'),
	url(r'^form/$', form_test),
	url(r'^test/$', test)

]

users/urls.py
from django.conf.urls import url

from .views import register,user_login, user_logout,profile,update,change_password
 
urlpatterns =[
	url(r'^register/$', register, name='register'),
	url(r'^user_login/$', user_login, name='user_login'),
	url(r'^change_password/$', change_password, name='change_password'),
	url(r'^user_logout/$', user_logout, name='user_logout'),
	url(r'^profile/(?P<pk>[0-9]+)/$', profile, name='profile'),
	url(r'^update/$', update, name='update'),

	
	
	
	]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}"/>
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}"/>
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-theme.css' %}"/>
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-theme.min.css' %}"/>

	
	<script src="{% static 'js/bootstrap.js' %}" type="text/javascript"></script> 
	<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script> 
	<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
	
	
	
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block title %} {% endblock %} </title>
	
	{% block kod %} {% endblock %}
	
</head>

<body>

<div class="jumbotron text-center" style="margin-bottom:0">
  <h1> olley olley olle de olley</h1>
 
</div>

<nav class="navbar navbar-inverse">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'post:index' %}">Ana Səhifə</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
	  
        <!--<li class="active"><a href="#">{% block link %} {% endblock %}<span class="sr-only">(current)</span></a></li> -->
		{% if request.user.is_authenticated %}
		<li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="{% url 'users:profile' request.user.pk %}"><img style="width:20px;height:20px;" class="img-circle" src="{{request.user.userprofile.photo.url}}"/> {{request.user.username}}
        <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="{% url 'users:profile' request.user.pk %}"><span class="glyphicon glyphicon-user"></span> Profil</a></li>
          <li><a href="{% url 'users:change_password' %}"><span class="glyphicon glyphicon-cog"></span> Parolu dəyiş</a></li>
		  <li role="separator" class="divider"></li>
		  <li><a href="{% url 'users:user_logout' %}"><span class="glyphicon glyphicon-log-out"></span> Log out</a></li>
          
        </ul>
      </li>
		{%endif%}
       
      </ul>
      <form class="navbar-form navbar-left" method="get" action='{% url "post:index" %}'>
        <div class="form-group">
			{% if request.GET.list %} <input type="hidden" name="list" value="{{ request.GET.list}}"/>{% endif %}
			{% if request.GET.cat_id %} <input type="hidden" name="cat_id" value="{{ request.GET.cat_id}}"/>{% endif %}
			<div class="input-group">
			
          <input type="text" class="form-control" name="key" placeholder="Axtar..." {% if request.GET.key %}value="{{request.GET.key}}"{% endif%} required>
        <span class="input-group-btn">
        <button class="btn btn-info" type="submit"><span class="glyphicon glyphicon-search"></span></button>
      </span></div></div>
      </form>
	  
      <ul class="nav navbar-nav navbar-right">
	  {% if request.user.is_authenticated %}
	  
        <li><form action="{% url 'post:create' %}" ><input type="submit" class="btn btn-success navbar-btn" value="Post yarat"/></form> </li>
		{% else %}
			<li><a href="{% url 'users:user_login' %}?next={{request.get_full_path}}"><span class="glyphicon glyphicon-log-in"></span> Log in</a></li>
			<li><a href="{% url 'users:register' %}"><span class="glyphicon glyphicon-plus"></span> Register</a></li>
		{% endif %}
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>



<div class="col-lg-8 col-md-8 col-sm-8 col-xs-12 col-lg-offset-2 col-md-offset-2 col-sm-offset-2 col-xs-offset-0"> 
<!--{% if messages %}

			{% for message in messages %}
			<div class="alert alert-{{ message.tags }} fade in text-center">
				{% block icon %} {% endblock %}{{message}}<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
				</div>
				{% endfor %} 
		 {% endif %} -->

{% block page %}
{% endblock %}

</div>

</body>

</html>

templates/messages.html
{% if messages %}
			{% for message in messages %}
			<div class="alert alert-{{ message.tags }} fade in">
				{% block icon %} {% endblock %}{{message}}<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
				</div>
				{% endfor %} 
		{% endif %}