learn/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from post.views import index
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^$', index),
	url(r'^post/', include('post.urls',namespace='post')),
	url(r'^users/', include('users.urls',namespace='users')),
	url(r'^todo/', include('todo.urls',namespace='todo')),
 ]
 
urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
 
urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.conf.urls import url
from .views import post_list, post_create, post_update, post_delete, post_detail, form_test, test, comment_delete, reply_view, like

urlpatterns =[
	url(r'^$', post_list, name='index'),
	url(r'^create/$', post_create, name='create'),
	url(r'^update/(?P<slug>[\w\-]+)/$', post_update, name='update'),
	url(r'^delete/(?P<slug>[\w\-]+)$', post_delete, name='delete'),
	url(r'^comment/delete/(?P<pk>[0-9]+)$', comment_delete, name='comment_delete'),
	url(r'^reply/(?P<pk>[0-9]+)$', reply_view, name='reply'),
	url(r'^like/(?P<pk>[0-9]+)$', like, name='like'),
	url(r'^detail/(?P<slug>[\w\-]+)/$', post_detail,name='detail'),
	url(r'^form/$', form_test),
	url(r'^test/$', test)

]

users/urls.py
from django.conf.urls import url

from .views import register,user_login, user_logout,profile,update,change_password
 
urlpatterns =[
	url(r'^register/$', register, name='register'),
	url(r'^user_login/$', user_login, name='user_login'),
	url(r'^change_password/$', change_password, name='change_password'),
	url(r'^user_logout/$', user_logout, name='user_logout'),
	url(r'^profile/(?P<pk>[0-9]+)/$', profile, name='profile'),
	url(r'^update/$', update, name='update'),

	
	
	
	]

post/models.py
from django.db import models
from django import forms
from django.utils.text import slugify
import random
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
#from .models import User


def upload_to(instance, filename):
	return '%s/%s/%s'%('post',instance.slug,filename)


class Category(models.Model):
	name=models.CharField(max_length=50,verbose_name='Kateqoriya')
	
	def __str__(self):
		return self.name
	
	class Meta:
		verbose_name='Kateqoriya'
		verbose_name_plural='Kateqoriyalar'

class Post(models.Model):
	author=models.ForeignKey(User, verbose_name='Müəllif',related_name='author')
	title=models.CharField(max_length=120, blank=False,verbose_name='Başlıq')
	slug=models.SlugField(max_length=120,default='', unique=True, null=False,verbose_name='Slug title', editable=False)
	post=RichTextField(verbose_name='Məqalə', blank=False)
	read=models.PositiveIntegerField(default=0)
	img= models.ImageField(blank=True, verbose_name='Post img',upload_to=upload_to)
	draft=models.BooleanField(default=False)
	category=models.ManyToManyField(Category, verbose_name='Kateqoriya')
	created_time=models.DateTimeField(auto_now_add=True)
	updated_time=models.DateTimeField(auto_now=True)
	
	def __str__ (self):
		return self.title
	
	def get_slug(self):
		return self.slug
	
	def unique_slug(self, new_slug, orginal_slug, index):
		exists = Post.objects.filter(slug=new_slug).exists()
		if exists:
			new_slug='%s-%s' %(orginal_slug,index)
			index +=1
			return self.unique_slug(new_slug=new_slug, orginal_slug=orginal_slug, index=index)
		return new_slug
		
	def save(self, *args, **kwargs):
		if self.slug =='':
			index=1
			new_slug=slugify(self.title)
			self.slug=self.unique_slug(new_slug=new_slug, orginal_slug=new_slug, index=index)
		super(Post,self).save(*args,**kwargs)
		
	
	def get_img_or_default(self):
		if self.img and hasattr(self.img,'url'):
			return self.img.url
		return '/staticfiles/img/default.png'
	
	def get_likes(self):
		likes=Like.objects.filter(post=self).count()
		return likes
	
	
	class Meta:
		verbose_name='Postlar'
		verbose_name_plural='Postlar'
		ordering=['-created_time']
		
		
class Comment(models.Model):
	post=models.ForeignKey(Post, verbose_name='comment',related_name='comment')
	sender=models.ForeignKey(User, verbose_name='sender',related_name='sender')
	text=models.TextField(verbose_name='Şərh',max_length=1200)
	date=models.DateTimeField(auto_now_add=True)
	
	class Meta:
		verbose_name='Şərh'
		verbose_name_plural='Şərhlər'
		ordering=['-date']
	'''def save(self,*args, **kwargs):
		text=self.text
		com_list=Comment.objects.filter(sender=self.sender)
		com_list=com_list.filter(text=text)
		if len(com_list) ==0:
			super(Comment,self).save(*args,**kwargs)'''
		
		
	def __str__(self):
		return '%s - %s'%(self.post,self.sender)

class Reply(models.Model):
	comment=models.ForeignKey(Comment,verbose_name='reply', related_name='reply')
	rsender=models.ForeignKey(User,verbose_name='sender',related_name='rsender')
	rtext=models.TextField(verbose_name='Cavab', max_length=1200)
	date=models.DateTimeField(auto_now_add=True)
	
	class Meta:
		verbose_name='Cavab'
		verbose_name_plural='Cavablar'
		ordering=['-date']
	def __str__(self):
		return '%s - %s'%(self.rsender, self.comment)

class Like(models.Model):
	post=models.ForeignKey(Post, verbose_name='like', related_name='like')
	sender=models.ForeignKey(User, verbose_name='sender',related_name='likesender')
	date= models.DateTimeField(auto_now_add=True)
	
	class Meta:
		verbose_name='Like'
		verbose_name='Likes'
		

post/forms.py
from django import forms
from .models import Post, Comment, Reply



class PostForm(forms.ModelForm):
	class Meta:
		model=Post
		fields=['title','post','category','img','draft']

	def __init__(self, *args, **kwargs):
		super(PostForm,self).__init__(*args, **kwargs)
		self.fields['title'].widget.attrs['class']='form-control'
		self.fields['post'].widget.attrs['class']='form-control'
		self.fields['category'].widget.attrs['class']='form-control'
		self.fields['img'].widget.attrs['class']='form-control'
		

class PostFilterForm(forms.Form):
	elements = (('all','All'),('draft', 'Only Drafts'),('nodraft', 'Not Drafts'))
	list=forms.CharField(widget=forms.Select(choices=elements, attrs={'class':'form-control','style':'width:auto;'}))
	
class CommentForm(forms.ModelForm):
	class Meta:
		model=Comment
		fields=['text']
		error_messages = {
            'text': {
                'max_length': ("Bu şərh çox uzundur. Maksimim 1200 simvol"),
            },
        }
	
	def __init__(self,*args,**kwargs):
		super(CommentForm,self).__init__(*args, **kwargs)
		self.fields['text'].widget.attrs['class']='form-control'

class ReplyForm(forms.ModelForm):
	class Meta:
		model=Reply
		fields=['rtext']
		error_messages = {
            'rtext': {
                'max_length': ("Bu cavab çox uzundur. Maksimim 1200 simvol"),
            },
        }
	
	def __init__(self,*args,**kwargs):
		super(ReplyForm,self).__init__(*args, **kwargs)
		self.fields['rtext'].widget.attrs['class']='form-control'
		self.fields['rtext'].widget.attrs['rows']='5'
		#self.fields['rtext'].widget.attrs['column']='1'		

post/views.py
from django.shortcuts import render,HttpResponse,HttpResponseRedirect,reverse,get_object_or_404,Http404
from .models import Post,Category, Comment, Reply, Like
from .forms import PostForm,PostFilterForm, CommentForm, ReplyForm
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.db.models import Q
import django
import jquery
from django.utils.text import slugify
from time import sleep
from django.core.paginator import Paginator,PageNotAnInteger,EmptyPage
from django.http import JsonResponse

def form_test(request):
	form= TestForm()
	mesaj=None
	if request.method=='POST':
		form=TestForm(request.POST)
		if form.is_valid:
			mesaj=form.data
	return render(request, 'post/form_test.html', context={'form': form,'mesaj':mesaj})
	

def index(request):
	return HttpResponseRedirect(reverse('post:index'))

@login_required(login_url='/users/user_login/')
def post_create(request):
	
	post_form=PostForm()
	if request.method == "POST":
		post_form=PostForm(request.POST, files=request.FILES or None)
		if post_form.is_valid():
			crepost=post_form.save(commit=False)
			crepost.author=request.user
			crepost.save()
			post_form.save_m2m()
			#post_form=PostForm()
			messages.success(request,'Post Yaradıldı',extra_tags='addpost')
			return HttpResponseRedirect(reverse('post:detail', kwargs={'slug':crepost.slug}))
		else:
			HttpResponseRedirect(reverse('post:index'))
	return render(request,'post/post_create.html',context={'form':post_form})

@login_required(login_url='/users/user_login/')
def post_update(request,slug):
	post=get_object_or_404(Post,slug=slug)
	title=post.title
	if post.author!=request.user:
		return HttpResponseRedirect(reverse('post:detail', kwargs={'slug':slug}))
	form=PostForm(data=request.POST or None, instance=post, files=request.FILES or None)
	if request.method == 'POST':
		if form.is_valid():
			if slugify(form.cleaned_data['title']) == slugify(title):
				form.save()
			else:
				crepost = form.save(commit=False)
				crepost.slug=''
				crepost.save()
				form.save_m2m()
			messages.success(request,'Post redaktə olundu!', extra_tags='postupdate')
			return HttpResponseRedirect(reverse('post:detail', kwargs={'slug':form.instance.slug}))
	return render(request, 'post/update.html', context={'form':form})

@login_required(login_url='/users/user_login/')
def post_delete(request,slug):
	post = get_object_or_404(Post,slug=slug)
	if post.author!=request.user:
		return HttpResponseRedirect(reverse('post:detail', kwargs={'slug':slug}))
	post.delete()
	messages.success(request,'Post silindi!',extra_tags='postdelete')
	return HttpResponseRedirect(reverse('post:index'))

@login_required(login_url='/users/user_login/')
def comment_delete(request,pk):
	comment = get_object_or_404(Comment,pk=pk)
	if request.user != comment.sender:
		return HttpResponseRedirect(reverse('post:detail', kwargs={'slug':comment.post.slug}))
	comment.delete()
	#messages.success(request,'Şərh silindi!',extra_tags='commentdelete')
	#return HttpResponseRedirect(reverse('post:detail', kwargs={'slug':comment.post.slug}))
	return JsonResponse(data={'success':'true'})
def post_list(request):
	filter_form=PostFilterForm(request.GET or None)
	posts_list= Post.objects.order_by('-created_time')
	page = request.GET.get('page', 1)
	cat_name=''
	cat_id = request.GET.get('cat_id','')
	author_id = request.GET.get('author_id','')
	key= request.GET.get('key','')
	if cat_id is not "":
		posts_list= Post.objects.filter(Q(category=cat_id))
		cat_name=Category.objects.filter(id=cat_id)
	if key is not "":		
		posts_list=posts_list.filter(title__icontains=key)
	if author_id is not '':
		posts_list=posts_list.filter(author=author_id)
			
	if filter_form.is_valid():
		list=request.GET.get('list', 'all')
		#filter_form.cleaned_data['list']
		if list == 'draft':
			posts_list=posts_list.filter(draft=True)
		elif list == 'nodraft':
			posts_list=posts_list.filter(draft=False)
		else:
			pass
	paginator = Paginator(posts_list, 4)
	try:
		posts_list = paginator.page(page)
	except PageNotAnInteger:
		posts_list = paginator.page(1)
	except EmptyPage:
		posts_list = paginator.page(paginator.num_pages)
	return render(request,'post/post_list.html', context={'post_list':posts_list,'filter_form':filter_form,'cat_name':cat_name,'key':key})

#@login_required(login_url='/users/user_login/')
def post_detail(request,slug):
	#post=Post.objects.get(pk=pk)  # Ən sadə üsul
	post=get_object_or_404(Post, slug=slug)
	'''post.read += 1
	post.save(editslug=False)'''
	comment_form=CommentForm()
	reply_form=ReplyForm()
	like=Like.objects.filter(sender=request.user,post=post).exists()
	if request.method == "POST":
		comment_form=CommentForm(request.POST)
		if comment_form.is_valid():
			comment=comment_form.save(commit=False)
			comment.post=post
			comment.sender=request.user
			
			comment.save()
			data={"success":"submit","text":comment.text,"pk":comment.pk,"sender":comment.sender.username,"avatar":comment.sender.userprofile.photo.url,"date":comment.date}
			comment_form=CommentForm()
			#return HttpResponseRedirect(reverse('post:detail', kwargs={'slug':post.slug}))
			return JsonResponse(data=data)
		else:
			return HttpResponseRedirect('#comments')
	return render(request,'post/detail.html', context={'post':post,'form':comment_form,'reply_form':reply_form,'like':like})

@login_required(login_url='/users/user_login/')
def reply_view(request,pk):
	comment=get_object_or_404(Comment, pk=pk)
	reply_form=ReplyForm(request.POST)
	if reply_form.is_valid():
		reply=reply_form.save(commit=False)
		reply.comment=comment
		reply.rsender=request.user
		reply.save()
		reply_form=ReplyForm()
		#return HttpResponseRedirect(reverse('post:detail', kwargs={'slug':comment.post.slug}))
		#return HttpResponseRedirect('/post/detail/'+comment.post.slug+'#comment')
		return JsonResponse(data={'success':'submit','pk':pk,'sender':reply.rsender.username,'text':reply.rtext,'date':reply.date})
	else:
		return HttpResponse('444')

@login_required(login_url='/users/user_login/')
def like(request,pk):
	post=get_object_or_404(Post, pk=pk)
	user=request.user
	like, created = Like.objects.get_or_create(sender=user, post=post)
	
	data={'success':None}
	if created:
		data['success']='like'
	else:
		like.delete()
		data['success']='unlike'
	dat = list(Like.objects.filter(post=post).values('sender'))
	userlist=[]
	for element in dat:
		pk=element['sender']
		username = User.objects.get(pk=pk).username
		userlist.append(username)
	data['names']=userlist
	return JsonResponse(data=data)
		
		
def test(request):
	return render(request, 'base.html')


	
	
	

templates/post/detail.html
{% extends 'base.html' %}

{% load static %}
{% block title %} {{post.title}} {% endblock %}



{% block kod %}

<script src="{% static 'js/dateformat.js' %}" type="text/javascript"></script>
<script src="{% static 'js/detail.js' %}" type="text/javascript"></script>

{% endblock %}


{% block page %}

{% if messages %}
			
			{% for message in messages %}
			{% if 'postupdate' in message.tags or 'addpost' in message.tags%}
			<div class="alert alert-success fade in text-center">
				{{message}}<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
				</div>
				{%endif%}
				{% endfor %} 
				
		 {% endif %}
		
		<div class="container-fluid ">
		<div class="text-center">
			<h1 class="page-header"> {{ post.title }}<br></h1>
			<form action="{% url 'post:index' %}" method="get" >
			{% for cat in post.category.all %} <input type='hidden' name="cat_id" value="{{cat.id}}"/> <input type="submit" value="{{ cat }}" class="btn btn-info"/>{% endfor %}</form><hr><p class="small">{{ post.created_time|timesince }} əvvəl
			{% if post.created_time != post.updated_time %}
				<br>{{post.updated_time|timesince  }} əvvəl redaktə olunub  
			{% endif %}</p>Müəllif: <strong><a href="{% url 'users:profile' post.author_id %}">{{post.author}}</a></strong> 
			<div class="text-justify"> {{ post.post|safe }} </div></div>
			<div class="media-center">
				<img src="{{post.get_img_or_default}}" class="img-responsive" style="max-width: 100%; display: block; height: auto;"/></div><br>
				<p><b>{{ post.read}}</b> dəfə oxunub</p>
				<!---------------------------------- LIKE ---------------------------------------->
				{% if request.user.is_authenticated %}
				{% if like %}
				
			<a id='likebtn' class="btn btn-danger" data-url="{% url 'post:like' post.pk %}" href="{% url 'post:like' post.pk %}"><span id="icon" class="glyphicon glyphicon-thumbs-down"></span></a> 
			{% else %}
			
			<a id='likebtn' class="btn btn-success" href="{% url 'post:like' post.pk %}"><span id="icon" class="glyphicon glyphicon-thumbs-up"></span></a> 
			{% endif %}
			<a id="likers" data-toggle="popover" data-trigger="hover" data-placement="bottom" data-html="true" data-content="{% for like in post.like.all %}{{like.sender }} <br/> {% endfor %}">
			<span class="glyphicon glyphicon-thumbs-up"></span> <span id="likenum">{{post.get_likes}}</span></a>
			
			
		
			{% endif %}
			<!----------------------------------------------/LIKE/------------------------------------->
			{% if request.user == post.author %}<br><br>
			<a class="btn btn-info" href="{% url 'post:update' post.slug %} "><span class="glyphicon glyphicon-pencil"></span>  Postu dəyiş</a>
			
			<button id="delslide" class="btn btn-danger"><span class="glyphicon glyphicon-trash"></span> Sil</button></div>
			<div id="del" class="collapse">
			<p class="lead text-center">əminsiz?<br>
			<a class="btn btn-danger" href="{% url 'post:delete' post.slug %} "> Postu Sil</a></p>
			</div>{% endif %}
	
		
		                               <!---------------------------------------  COMMENT ------------------------------------------->   
		<div id="comments" class="container-fluid">

			<h2 class="page-header"> Şərhlər (<span id="sumcomment">{{post.comment.all|length}}</span>)</h2>
			
			<div class='col-lg-10 col-lg-offset-1'>
			{% if request.user.is_authenticated %}
			<form id="commentform" action="{% url 'post:detail' post.slug %}" method="post">
				{% csrf_token %}
				
				{% for field in form %}
					<div class="form-group">
				
				{{ field.label_tag }}<br>
				{{field.errors}}
				{{field}} <br>
				{% endfor %}
				<input type="submit" id="subcomment" class="btn btn-info" value="Yaz"/></div>
			</form>
			
			
			{% else %}
				<div class="alert alert-warning text-center">
				Şərh yazmaq üçün <strong><a href="{% url 'users:user_login' %}?next={% url 'post:detail' post.slug %}">Daxil ol</a></strong>un
				</div>
			{% endif %}
			<hr>
			<div class="col-lg-12">
			<!------------------------------------- MESSAGES -------------------
			
			<div id="messagediv" style="display: none;"class="alert alert-danger fade in text-center">
				<span id="message"></span><a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
				</div>
				-->
			
				<!--------------------------------/MESSAGES----------------------->
				
					<div id="commentsblock" class="row">
				{% for comment in post.comment.all %}
				<div id="bigcomment" class="col-lg-12">
				
				
						<div class="col-lg-1">
							
						<img id="imgcomment" src="{{comment.sender.userprofile.photo.url}}" style="width:40px; height:40px;" class="img-responsive img-circle"/>
						</div> 
							<div id="comment" class="col-lg-11"><h4><b>{{comment.sender}}</b><small> {{comment.date}}</small>
							{% if request.user == comment.sender %}
							<a class="btn btn-danger comdelete" href="{% url 'post:comment_delete' comment.pk %}">  <span class="glyphicon glyphicon-trash"></span></a>
							{% endif %}{% if request.user.is_authenticated %}
							<button class="btn btn-success" data-toggle="collapse" data-target="#reply{{comment.pk}}">
							<span class="glyphicon glyphicon-share-alt"></span></button>
							{% endif %}<button class="btn btn-info" data-toggle="collapse" data-target="#replies{{comment.pk}}">
							<span class="glyphicon glyphicon-collapse-down"></span></button> </h4>
							<p>{{comment.text}}</p>
							<hr>
							
					<!------------------------------- REPLY ---------------------->
					<div class="col-lg-12">
					{% if request.user.is_authenticated %}
					
					<div id="reply{{comment.pk}}" class="collapse">
						<form id="reply" class="replyform" action="{% url 'post:reply' comment.pk %}" method="post">
								{% csrf_token %}
					
								{% for field in reply_form %}
							<div class="form-group">
							{{ field.label_tag }}<br>
							{{field.errors}}
							{{field}} <br>
								{% endfor %}
							<input type="submit" id ="replysub" class="btn btn-info replysub" value="Yaz"/></div>
						</form>
					</div>
					
					{% endif %}

							<div id="replies{{comment.pk}}" class="collapse">
						{% for reply in comment.reply.all %}
					
							
						<h5><strong>{{reply.rsender}}</strong> <small>[{{reply.date}}]</small></h5>
						<p>{{reply.rtext}} </p>
						
				
							
							
							
						{% endfor %}</div> <!-- collapse -->
						</div> <!-- col-lg-12 -->
								
							</div> <!--col-lg-11 #comment -->

								</div> <!--col-lg-12 #bigcomment-->
							
					<!---------------------------------------------- END REPLY ----------------------------------------->
					
					{% empty %}
						<div class="alert alert-info text-center">
							İlk şərhi <strong>SƏN</strong> Yaz 
						</div>
					{% endfor %}
				</div> <!-- row #commentsblock-->
					</div>
				</div>
					
				
				
		</div>
		
{% endblock %}

templates/post/form_test.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Form {% endblock %}
{% block page %}

	<div class="col-lg-4 col-lg-offset-4">
		<form action="" method="post">
		<div class="form-group">
			{% csrf_token %}
			{% for field in form %}
				{{ field.label_tag }}
				{{field}} 
			{% endfor %}</div>
			<input type="submit" class="btn btn-primary" value="Göndər"/>
	</form>
	
	{%if mesaj != None %}
	Mesaj: {{ mesaj }}
	{% endif %}
	</div>

{% endblock %}

templates/post/post_create.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Post yarat{% endblock %}
{% block kod %}

<script>

$(document).ready(function(){
		$("#sub").click(function(e){
		e.preventDefault();
		if ($("#id_title").val() != "" && $("#id_category").val() != ""){
		
		$("#postform").submit();
		$('#sub').prop('disabled', true);
		} else{
		alert("Xanaları doldurun");
		}
		}); 
	});

</script> 

{% endblock %}
{% block page %}
	
	<h2 class="page-header">Post Yarat</h2>
	<div class="col-lg-10 col-lg-offset-1">
		<form id="postform" action="" enctype="multipart/form-data" method="post" >
			{% csrf_token %}
			{{ form.media }}
			{% for field in form %}
				<div class="form-group">
				
				{{ field.label_tag }}
				{{field}} </div>
				
			{% endfor %}
			
			
			<input id="sub" class="btn btn-primary" type="submit" value="Göndər"/>
		</form>
	
		</div>
		
{% endblock %}

templates/post/post_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Ana Səhifə {% endblock %}

{% block icon %} <span class="glyphicon glyphicon-trash"></span>{% endblock %}
{% block page %}




<div class="container-fluid">
{% if messages %}
			
			{% for message in messages %}
			{% if 'postdelete' in message.tags %}
			<div class="alert alert-danger fade in text-center">
				{{message}}<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
				</div>
				{%endif%}
				{% endfor %} 
				
		 {% endif %}

<div class="col-lg-12">

<h3 class="text-center">{% if cat_name %}
Kateqoriya: <span class="label label-info">{{cat_name.0}}<a href="/post{% if request.GET.key %}?key={{request.GET.key}}&{% else%}?{% endif %}{% if request.GET.list %}list={{request.GET.list}}{% endif %}" > <span class="glyphicon glyphicon-remove-circle"></span></a></span><br><br>
{% endif %}
{% if key %}
Axtarış: <span class="label label-info">{{key}}<a href="/post{% if request.GET.cat_id %}?cat_id={{request.GET.cat_id}}&{% else%}?{% endif %}{% if request.GET.list %}list={{request.GET.list}}{% endif %}" > <span class="glyphicon glyphicon-remove-circle"></span></a></span><br><br>
{% endif %}
Postlar <span class="label label-success">{{ post_list|length }}/{{post_list.paginator.count}}</span>
</h3>
{% if filter_form %}
<form class="form-inline" method='get'>
<div class="form-group">
{% if request.GET.key %} <input type="hidden" name="key" value="{{ request.GET.key}}"/>{% endif %}
{% if request.GET.cat_id %} <input type="hidden" name="cat_id" value="{{ request.GET.cat_id}}"/>{% endif %}
{%for field in filter_form %}
{{field}}
{% endfor %}
<input type="submit" value="OK" class="btn btn-info"/></div>
</form>{% endif %}<hr>
</div>

<div class="panel-group">
<div class="col-lg-12">

{% for post in post_list %}

<div class="panel panel-default" style="display:block">
	<div style="display:block" class="panel-heading text-center"><p class="lead"><a href="{% url 'post:detail' post.get_slug %}">{{post.title}}</a>
		{% if post.draft %}
	<span class='text-right'>|D</span>
	{% endif %}</p></div>
	<div class="panel-body"><p class="text-info"><small>{{post.created_time}}</small>
		Kateqoriya: {% for cat in post.category.all %} {{cat}} {% endfor %}<br></p>
     {{ post.post|safe|truncatewords_html:5 }}
	</div></div><br>
	{% empty %}

		<div class="alert alert-warning text-center">
			<strong>Post Yoxdur!</strong>
		</div>
		
{% endfor %}</div>
</div>
<div class="col-lg-12">
{% if post_list.has_other_pages %}
  <ul class="pagination">
    {% if post_list.has_previous %}
      <li><a href="?page={{ post_list.previous_page_number }}{% if request.GET.list %}&list={{ request.GET.list}}{% endif %}{% if request.GET.key %}&key={{ request.GET.key}}{% endif %}{% if request.GET.cat_id %}&cat_id={{ request.GET.cat_id}}{% endif %}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in post_list.paginator.page_range %}
      {% if post_list.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}{% if request.GET.list %}&list={{ request.GET.list}}{% endif %}{% if request.GET.key %}&key={{ request.GET.key}}{% endif %}{% if request.GET.cat_id %}&cat_id={{ request.GET.cat_id}}{% endif %}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if post_list.has_next %}
      <li><a href="?page={{ post_list.next_page_number }}{% if request.GET.list %}&list={{ request.GET.list}}{% endif %}{% if request.GET.key %}&key={{ request.GET.key}}{% endif %}{% if request.GET.cat_id %}&cat_id={{ request.GET.cat_id}}{% endif %}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}
</div>
</div>


{% endblock %}

templates/post/test.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
{% block page %}

{% for cat in post_list %}
{{cat}}
{% endfor %}

{% endblock %}

templates/post/update.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Ana Səhifə {% endblock %}
{% block page %}

		<h2 class="page-header">Post Redaktə</h2>
	<div class="col-lg-10 col-lg-offset-1">
		<form action="" enctype="multipart/form-data" method="post">
			{% csrf_token %}
			{{form.media}}
			{% for field in form %}
				<br>
				{{ field.label_tag }}
				{{field}}
				<br>
			{% endfor %}
			<br>
			<input class="btn btn-primary" type="submit" value="Göndər"/>
		</form>
		</div>
	
	
		
{% endblock %}