learn/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from post.views import index
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^$', index),
	url(r'^post/', include('post.urls',namespace='post')),
	url(r'^users/', include('users.urls',namespace='users')),
	url(r'^todo/', include('todo.urls',namespace='todo')),
 ]
 
urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
 
urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.conf.urls import url
from .views import post_list, post_create, post_update, post_delete, post_detail, form_test, test, comment_delete, reply_view, like

urlpatterns =[
	url(r'^$', post_list, name='index'),
	url(r'^create/$', post_create, name='create'),
	url(r'^update/(?P<slug>[\w\-]+)/$', post_update, name='update'),
	url(r'^delete/(?P<slug>[\w\-]+)$', post_delete, name='delete'),
	url(r'^comment/delete/(?P<pk>[0-9]+)$', comment_delete, name='comment_delete'),
	url(r'^reply/(?P<pk>[0-9]+)$', reply_view, name='reply'),
	url(r'^like/(?P<pk>[0-9]+)$', like, name='like'),
	url(r'^detail/(?P<slug>[\w\-]+)/$', post_detail,name='detail'),
	url(r'^form/$', form_test),
	url(r'^test/$', test)

]

users/urls.py
from django.conf.urls import url

from .views import register,user_login, user_logout,profile,update,change_password
 
urlpatterns =[
	url(r'^register/$', register, name='register'),
	url(r'^user_login/$', user_login, name='user_login'),
	url(r'^change_password/$', change_password, name='change_password'),
	url(r'^user_logout/$', user_logout, name='user_logout'),
	url(r'^profile/(?P<pk>[0-9]+)/$', profile, name='profile'),
	url(r'^update/$', update, name='update'),

	
	
	
	]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
import os
import random

# Create your models here.
def upload_to(instance, filename):
	filename, file_extension = os.path.splitext(filename)
	return '%s/%s/avatar%s%s'%('users',instance.user.username,random.randrange(100,999),file_extension)

class UserProfile(models.Model):
	MALE='1'
	FEMALE='2'
	SEX=((MALE,'Kişi'),(FEMALE,'Qadın'))
	user=models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='User')
	bio=models.TextField(max_length=200,verbose_name='Haqqında', blank=True, null=True)
	tel=models.CharField(max_length=14, verbose_name='Telefon Nömrəsi', blank=True, null=True)
	tarix=models.DateField(verbose_name='Doğum Tarixi', blank=True, null=True)
	sex=models.CharField(verbose_name='Cins', max_length=1, choices=SEX, blank=True, null=True)
	photo=models.ImageField(verbose_name='Avatar',blank=True, upload_to=upload_to, default='pp_default.jpg', null=True)
	
	class Meta:
		verbose_name='Profil'
		verbose_name_plural='Profillər'
	
	def __str__(self):
		return '%s - %s'%(self.user.username,'Profil')

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm

from .models import UserProfile

class RegisterForm(UserCreationForm):
	class Meta:
		model=User
		fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )
		#fields=['first_name','last_name','username','email','password1','password2']
	def __init__(self, *args, **kwargs):
		super(RegisterForm,self).__init__(*args, **kwargs)
		self.fields['first_name'].widget.attrs['class']='form-control'
		self.fields['last_name'].widget.attrs['class']='form-control'
		self.fields['email'].widget.attrs['class']='form-control'
		self.fields['email'].widget.attrs['required'] = 'required'
		self.fields['password1'].widget.attrs['class']='form-control'
		self.fields['password2'].widget.attrs['class']='form-control'
		self.fields['username'].widget.attrs['class']='form-control'
	
	def clean_email(self):
		email=self.cleaned_data['email'].lower()
		username=self.cleaned_data['username'].lower()
		if email!='' and email!=username:
			mail_list=User.objects.filter(email=email)
			if len(mail_list)==0:
				return email
			else:
				raise forms.ValidationError('Bu email istifade olunub')
		else:
			raise forms.ValidationError('Email düzgün yazılmalıdır')

class LoginForm(forms.Form):
	username=forms.CharField(max_length=150, label='İstifadəçi adı/email',required=True,widget=forms.TextInput(attrs={'class':'form-control'}))
	password=forms.CharField(required=True, label='Parol', widget=forms.PasswordInput(attrs={'class':'form-control'}))
	
	def clean_username(self):
		username=self.cleaned_data['username']
		mail_list=User.objects.filter(email=username.lower())
		if len(mail_list) ==1:
			user=mail_list.first()
			return user.username
		elif len(mail_list)==0:
			return username
		else:
			return username


class ProfileForm(forms.ModelForm):
	tarix = forms.DateField(label='Doğum Tarixi',help_text='Belə yazın: 31-12-0000',input_formats=['%d-%m-%Y'],widget=forms.DateInput())
	class Meta:
		model=UserProfile
		type='test'
		fields=('bio','tel','tarix','sex','photo')
	
	
	def __init__(self, *args, **kwargs):
		super(ProfileForm,self).__init__(*args, **kwargs)
		#self.fields['tarix'].widget=DateTimePicker(options={"format": "YYYY-MM-DD", "pickTime":False})
		self.fields['bio'].widget.attrs['class']='form-control'
		self.fields['tel'].widget.attrs['class']='form-control'
		self.fields['tarix'].widget.attrs['class']='form-control'
		self.fields['sex'].widget.attrs['class']='form-control'
		self.fields['photo'].widget.attrs['class']='form-control'

class UserForm(forms.ModelForm):
	class Meta:
		model= User
		fields = ('username','first_name','last_name','email')
		
	def __init__(self, *args, **kwargs):
		super(UserForm,self).__init__(*args, **kwargs)
		self.fields['username'].widget.attrs['class']='form-control'
		self.fields['first_name'].widget.attrs['class']='form-control'
		self.fields['last_name'].widget.attrs['class']='form-control'
		self.fields['email'].widget.attrs['class']='form-control'
		
class CustomPasswordForm(PasswordChangeForm):
	def __init__(self, *args, **kwargs):
		super(CustomPasswordForm,self).__init__(*args,**kwargs)
		self.fields['old_password'].widget.attrs['class']='form-control'
		self.fields['new_password1'].widget.attrs['class']='form-control'
		self.fields['new_password2'].widget.attrs['class']='form-control'

users/views.py
from django.shortcuts import render,HttpResponse,HttpResponseRedirect,reverse,get_object_or_404,Http404
from django.contrib import messages
from .forms import RegisterForm,LoginForm,ProfileForm,UserForm,CustomPasswordForm
from django.contrib.auth import update_session_auth_hash
from django.db.models import Q
from django.core.paginator import Paginator,PageNotAnInteger,EmptyPage
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.models import User
from post.models import Post,Category
from .models import UserProfile
from django.contrib.auth.decorators import login_required


# Create your views here.

def profile(request,pk):
	user_list=User.objects.all()
	user=user_list.get(pk=pk)
	return render(request,'users/profile.html', context={'user':user,'user_list':user_list})

@login_required(login_url='/users/user_login/')
def update(request):
	profile=UserProfile.objects.get(user_id=request.user.pk)
	profile_form=ProfileForm(data=request.POST or None, instance=profile,files=request.FILES or None)
	user_form=UserForm(data=request.POST or None, instance=request.user)
	if user_form.is_valid() and profile_form.is_valid():
		user_form.save(commit='True')
		profile_form.save(commit='True')
		messages.success(request,'Profil redaktə olundu!',extra_tags='profilupdate')
		return HttpResponseRedirect(reverse('users:profile', kwargs={'pk':request.user.pk}))
	return render(request,'users/update.html', context={'profile_form':profile_form,'user_form':user_form})

@login_required(login_url='/users/user_login/')
def change_password(request):
	if request.method == 'POST':
		form = CustomPasswordForm(request.user, request.POST)
		if form.is_valid():
			user = form.save()
			update_session_auth_hash(request, user)  # Important!
			messages.success(request, 'Parolunuz Dəyişdirildi',extra_tags='changepass')
		else:
			messages.error(request, 'Xanaları düzgün doldurun', extra_tags='passerror')
	else:
		form = CustomPasswordForm(request.user)
	return render(request,'users/change_password.html', context={'form':form})
		
def register(request):
	if request.user.is_authenticated():
		return HttpResponseRedirect(reverse('post:index'))
	form=RegisterForm(request.POST or None)
	
	if form.is_valid():
		user=form.save(commit=False)
		username=form.cleaned_data['username']
		password=form.cleaned_data['password1']
		user.set_password(password)
		user.save()
		user = authenticate(username=username, password=password)
		login(request,user)
		return HttpResponseRedirect(reverse('post:index'))
	return render(request,'users/register.html', context={'form':form})
	
def user_login(request):
	next=request.GET.get('next', '')
	if request.user.is_authenticated():
		return HttpResponseRedirect(reverse('post:index'))
	form=LoginForm(request.POST or None)
	if form.is_valid():
		next=request.POST.get('next', '')
		username=form.cleaned_data['username']
		password=form.cleaned_data['password']
		user = authenticate(username=username, password=password)
		if user:
			login(request,user)
			if next != '':
				return HttpResponseRedirect(next)
			return HttpResponseRedirect(reverse('post:index'))
		else:
			error='İstifadəçi adı/email və ya parol səhvdir'
			return render(request,'users/login.html', context={'form':form,'error':error,'next':next})
	return render(request,'users/login.html', context={'form':form,'next':next})

def user_logout(request):
	logout(request)
	return HttpResponseRedirect(reverse('post:index'))
	
	
	
	
	
	

templates/users/change_password.html
  {% extends 'base.html' %}
{% block title %}Profil: {{user.username}}{% endblock %}
{% block page %}
{% if messages %}
			
			{% for message in messages %}
			{% if 'changepass' in message.tags %}
			<div class="alert alert-success fade in text-center">
				{{message}}<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
				</div>
			{% elif 'passerror' in message.tags %}
			<div class="alert alert-danger fade in text-center">
				{{message}}<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
				</div>
				{%endif%}
				{% endfor %} 
				
		 {% endif %}
<h2 class="page-header">Parolu Dəyiş</h2>
<div class="col-lg-6 col-lg-offset-1">
{% if error %}
<div class="alert alert-danger fade in text-center">
				{{error}}<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
				</div>{% endif %}
		<form action="" method="post" enctype="multipart/form-data">
	{% csrf_token %}
	{{form.as_p}}
	
<input type="submit" value="Dəyiş" class="btn btn-success"/>
</form>
</div>
{% endblock %}

templates/users/login.html
{% extends 'base.html' %}

{% block page %}
<h2 class="page-header">Login</h2>
<div class="col-lg-6 col-lg-offset-1">
{% if error %}
<div class="alert alert-danger fade in text-center">
				{{error}}<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
				</div>{% endif %}
				<div class="alert alert-warning text-center">Hesabın Yoxdur? <a href="{%url 'users:register'%}">Qeydiyyat</a></div>
<form action="{% url 'users:user_login' %}" method="post">
	{% csrf_token %}
	{{form.as_p}}<br>
<input type="hidden" name='next' value='{{next}}'/>
<input type="submit" value="Login" class="btn btn-success"/>
</form>

</div>

{% endblock %}

templates/users/profile.html
{% extends 'base.html' %}

{% load static %}
{% block title %}Profil: {{user.username}}{% endblock %}


{% block page %}
{% if messages %}
			
			{% for message in messages %}
			{% if 'profilupdate' in message.tags %}
			<div class="alert alert-success fade in text-center">
				{{message}}<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
				</div>
				{%endif%}
				{% endfor %} 
				
		 {% endif %}
<div class="container-fluid">
<div class="row">
<div class="col-lg-8">
<h2 class="page-header"><a href="#" class="btn btn-warning">{{user.pk}}</a> {{ user.username}}<small> {{ user.date_joined|timesince}} əvvəl bizə qatılıb</small>
{% if user.username == request.user.username %}
<a href="{% url 'users:update'%}" class="btn btn-default close"><span class="glyphicon glyphicon-pencil"></span></a>{% endif %}</h2>
<div class="row">
<div class="col-lg-4">

<p class="lead"> <img class="img-responsive" style="border: 2px solid; width: 100%; display: block; height: 100%;" src="{{user.userprofile.photo.url}}"/> 
<br><br>{{user.get_full_name}}</p>
{{ user.sender.all|length }} şərh yazıb<br>
Şərhlərə {{ user.rsender.all|length }} cavab yazıb<br>


</div>
<div class="col-lg-8">
{% if user.last_login %}<p> Sonuncu dəfə {{user.last_login|timesince}} əvvəl daxil olub</p> {% endif %}
{% if user.email %}<p>Email: {{user.email}}</p> {% endif %}
{% if user.userprofile.bio %}<p>Haqqında: <br>  {{user.userprofile.bio|linebreaks}} </p><hr>{% endif %}
{% if user.userprofile.tel %}<p>Telefon: <br>  {{user.userprofile.tel}} </p><hr>{% endif %}
{% if user.userprofile.sex %}<p>Cins: <br>{% if user.userprofile.sex == '1' %} Kişi {% elif user.userprofile.sex == '2' %} Qadın {% endif %} </p><hr>{% endif %}
{% if user.userprofile.tarix %}<p>Doğum tarixi: <br>  {{user.userprofile.tarix}} </p><hr>{% endif %}
{% if user.is_superuser %}<button class="btn btn-danger">ADMİN</button>{% endif%}
{% if user.is_staff %}<button class="btn btn-success">STAFF</button>{% endif%}
</div>
</div>
<h3 class="page-header">Postları({{user.author.all|length}}) </h3>

<div class="col-lg-12">
<table class="table table-striped text-center"> 
<tbody>
{% for post in user.author.all %}

  <!---->
 
      <tr>
        <td><a href="{% url 'post:detail' post.slug%}"><h4>{{post.title}}</h4></a><small> {{post.created_time}}</small></td>
      </tr>

{% endfor %}
</tbody>
</table>
<hr>
</div>
</div>
<div class="col-lg-4">
<h2 class="page-header">Digər istifadəçilər</h2>
<table class="table table-striped text-center"> 
<tbody>
{% for user in user_list%}
<tr>
<td><a href="{% url 'users:profile' user.id %}"><h4>{{user}}</h4></a></td>
</tr>
{% endfor %}
</tbody>
</table>
</div>
</div>
</div>
{% endblock %}

templates/users/register.html
{% extends 'base.html' %}

{% block page %}
<h2 class="page-header">Register</h2>
<div class="col-lg-6 col-lg-offset-1">
<div class="alert alert-warning text-center">Hesabın Var? <a href="{%url 'users:user_login'%}">Daxil ol</a></div>
<form action="" method="post">
	{% csrf_token %}
	{% for field in form %}
		{{field.label_tag}}
		{{field}}
		{{field.errors}}
	{% endfor %}<br>

<input type="submit" value="Register" class="btn btn-success"/>
</form>

</div>

{% endblock %}

templates/users/update.html
 {% extends 'base.html' %}
{% block title %}Profil: {{request.user.username}}{% endblock %}
{% block page %}
<h2 class="page-header">Profil Redaktə: <a href="{% url 'users:profile' request.user.pk %}">{{request.user.username}}</a></h2>
<div class="col-lg-6 col-lg-offset-1">
{% if error %}
<div class="alert alert-danger fade in text-center">
				{{error}}<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
				</div>{% endif %}
		<form action="" method="post" enctype="multipart/form-data">
	{% csrf_token %}
	{{user_form.as_p}}
	{{profile_form.as_p}}<br>
	
<input type="submit" value="Dəyiş" class="btn btn-success"/>
</form>
<hr>
</div>
{% endblock %}